### ISSUE TITLE
id3 related crash

### ISSUE THREAD

**Issue by reflog** [mjibson/mog#5]
here's a stacktrace.

2015/02/20 12:45:16 http: panic serving [::1]:5182: EOF
goroutine 16 [running]:
net/http.func·011()
        /usr/src/go/src/net/http/server.go:1130 +0xc2
github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3.skipBytes(0xc0834e3800, 0x37573)
        /go/src/github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3/util.go:156 +0xf2
github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3.parseID3v24File(0xc0834e3800, 0xc082067540)
        /go/src/github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3/id3v24.go:53 +0x2ad
github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3.Read(0xef0a50, 0xc0820ea1a0, 0xc0820ea1a0)
        /go/src/github.com/mjibson/mog/_third_party/github.com/ascherkus/go-id3/src/id3/id3.go:70 +0x1ff
github.com/mjibson/mog/codec/mpa.(*Song).Info(0xc0820d2a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/mjibson/mog/codec/mpa/mpa.go:86 +0x26d
github.com/mjibson/mog/protocol/file.func·001(0xc0820cec30, 0x41, 0xee24c8, 0xc0834e2c60, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/protocol/file/file.go:101 +0x415
path/filepath.walk(0xc0820cec30, 0x41, 0xee24c8, 0xc0834e2c60, 0xc082173858, 0x0, 0x0)
        /usr/src/go/src/path/filepath/path.go:347 +0x98
path/filepath.walk(0xc082096a80, 0x25, 0xee24c8, 0xc082381aa0, 0xc082173858, 0x0, 0x0)
        /usr/src/go/src/path/filepath/path.go:372 +0x524
path/filepath.walk(0xc0820c0fa0, 0x11, 0xee24c8, 0xc0833f1860, 0xc082173858, 0x0, 0x0)
        /usr/src/go/src/path/filepath/path.go:372 +0x524
path/filepath.walk(0xc08335de70, 0x8, 0xee24c8, 0xc0833f0840, 0xc082173858, 0x0, 0x0)
        /usr/src/go/src/path/filepath/path.go:372 +0x524
path/filepath.Walk(0xc08335de70, 0x8, 0xc082173858, 0x0, 0x0)
        /usr/src/go/src/path/filepath/path.go:394 +0xf9
github.com/mjibson/mog/protocol/file.(*File).Refresh(0xc082092460, 0xc082131858, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/protocol/file/file.go:115 +0x8e
github.com/mjibson/mog/protocol.Instance.Refresh·fm(0xc082045948, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/server/server.go:275 +0x52
github.com/mjibson/mog/server.(*Server).protocolRefresh(0xc0820801e0, 0xc08205f589, 0x4, 0xc082131858, 0x8, 0xc0820a3c00, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/server/server.go:279 +0x1d2
github.com/mjibson/mog/server.(*Server).ProtocolRefresh(0xc0820801e0, 0xc0820a3c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/server/web.go:159 +0x123
github.com/mjibson/mog/server.*Server.ProtocolRefresh·fm(0xc0820a3c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/server/web.go:43 +0x80
github.com/mjibson/mog/server.func·030(0xee8ac0, 0xc082211040, 0xc0820c61a0, 0x0, 0x0, 0x0)
        /go/src/github.com/mjibson/mog/server/web.go:74 +0xd4
github.com/mjibson/mog/_third_party/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc082092000, 0xee8ac0, 0xc082211040, 0xc0820c61a0)
        /go/src/github.com/mjibson/mog/_third_party/github.com/julienschmidt/httprouter/router.go:293 +0x195
net/http.(*ServeMux).ServeHTTP(0xc08209a120, 0xee8ac0, 0xc082211040, 0xc0820c61a0)
        /usr/src/go/src/net/http/server.go:1541 +0x184
net/http.serverHandler.ServeHTTP(0xc08209e780, 0xee8ac0, 0xc082211040, 0xc0820c61a0)
        /usr/src/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc082210fa0)
        /usr/src/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        /usr/src/go/src/net/http/server.go:1751 +0x365

**Comment by mjibson** [comment]
Is the source mp3 on the internet somewhere?

**Comment by reflog** [comment]
https://www.dropbox.com/s/w6oir29chjblvyv/02%20Cemeteries%20of%20London.mp3?dl=0
